apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WJfsHGccPQMzfQCQDAIXLyPQ6FowDBPdXIF8RKDlpkOOzTSIdXjt77ltfaIfjIn03SeWwsVPurPT/Ys2HV0fDIk=,iv:n836A7SaoYBgwRBiShl6f9w8f1JLZAt9SxkMr/fbPuA=,tag:3Ygpctg7L6Ckj7In/tpgGg==,type:comment]
    #ENC[AES256_GCM,data:USD+E5UQ5D3Sa3c3TF8lWbMU/pqBSt8spD2p0N78VW6gt7/1kZCfkZJFMD8=,iv:8+MRQkQTMj+MzPnioqQ7C9xWGB+DJwBKYVqCjen2eNw=,tag:92UqpQDw3aGb7VWMgYoq3A==,type:comment]
    VIP: ENC[AES256_GCM,data:n5UorbKTS7BY,iv:viKfyvtPz3W1jdQNWel4iUM+cIgQ01ZS9mHSzn5qsJY=,tag:aRS9U4zfO1A2nAc0iJ5e0w==,type:str]
    #ENC[AES256_GCM,data:3HyINayypQ8rhzuNDCWDU75tfvtLJIqgYmA=,iv:m9Ryj4W4WjdikmZmUB/eqj0xMxMLD4fpsiozI9EhVqI=,tag:gsF8psc2gD6oa1OsAEBWnA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:9MTVuwkvLZbQ,iv:mcM7OTrymH3OcViSJWkBplSehrthzCioTr7XBkZiYiI=,tag:nKcTCWvfuQjKbFxvTy7qhQ==,type:str]
    #ENC[AES256_GCM,data:M30pe3qqRP2Hn9OjIljmv+lJ5CCBtw78pPVimJUMdPM+Cg==,iv:+ksgA9rvMm03KJnwK4ILVdLHYgvOYGxgZmp25839NP0=,tag:NlO8FYtFfDXcZkYJJqu6eg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:J/NJAMYY/yM=,iv:Jx6PjAzgIXX5hN6c+3uM952V/reRitYBg5yfwRp4c18=,tag:q0OXhBXqFCmCfCLCYqLucg==,type:str]
    #ENC[AES256_GCM,data:eiRKmwqYRlH7gvw2ygK4u7uyWQyB73tlhMvP4v55Sl3obUvLWqeOxMDAtBFdNwc=,iv:4nRNEslBXixAjdhRUBPMn9Dp6o8G88Ay5el6IEpeT3g=,tag:DucqRE+pqhfzFV6ZZ8lJ4w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:HmwovCFrpR/D87o6y5Q1Cjj2Zw==,iv:tXiWVcOmZDoCpmVIFOQuVhJONKMQSrNWjpZZUN6YIyo=,tag:47832PMpFAPa9ydgCGXfoA==,type:str]
    #ENC[AES256_GCM,data:N1GzY6GNC+fHFDxVP2gJ2fiNW/lvG/0NW9ZkKzNLe4trGKMcshZJOIhscn8B8hWNDoiXyWRipzLW4VwLl2gpC87NCI+Ay4x9qMz99ze+7oM=,iv:KEBguDCsSw4SwTTWfRDoek5p0AGMsEKdy3XnpDwyuhI=,tag:e5HnG13r2YCGZBG1UDl60A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:jlkbVYo9BF7E,iv:DQcArtNQGIYYIQ3t+QMIHjQsUtCyvistWO4YXDuczRs=,tag:qJZUCMV/qFA4zI2sQh1reA==,type:str]
    #ENC[AES256_GCM,data:Cf9el3Jup7o7qzgmfea2FUmsbwb3qf+38xpAcdPH3l3wADHLkrt2JA80g3I2JBntVjpF2LCU18s=,iv:t0tu3cU+z8XVbra20YzZ03baSipeeqTSxLEvG8Kd66g=,tag:Mc94hpobKHoqQ3Pzrf5j7A==,type:comment]
    #ENC[AES256_GCM,data:p4M0lGuDzEsCEzUdfvnorrwM59Iapy4LFw==,iv:oFgCw2koG1zVvQ6u4frptsV4ePoH+cX04JVa4NF1yhg=,tag:p8njq1BFSHspXQSMPEfMzQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:vGn/Tc0Sfu2FSRRPPLNlgKHNaGYvdNcwyuP4IIRv/xsQhGxyOk6LBZb0Y/2vfg==,iv:iiGLhuol/tCXi8KaK5P3VTdCgY6KI3b0IU68nV3gQqI=,tag:fT90WoX9XIVivOXg/dUr2Q==,type:str]
    #ENC[AES256_GCM,data:xrrZNYrrAhym5+Uiyz7BQeyoHPWGcPkROJejKAfwNLHvkPTpT6SyEnFInsCEqwxvLxfHg7XadBumkSYEnCe3GOo43gFoP7U=,iv:87jE19GJNfiIVXcOvtC16zEXVTwzZTZpBxhHoLewFHY=,tag:EG4H5vv/5jsJSAdFTrj+Vg==,type:comment]
    #ENC[AES256_GCM,data:kTf4jGPAAYsdLp4C8DMBZ/iQC/OPGT90L8G3nQ4FW9txzLCVsobNnDnJSEJnRA9HTZfD5Dp4,iv:ptgmMp+RduMBACjzaLatKvnqQMjQhdZkkm8aAZ7FIZA=,tag:tl+SXDi4uj7oIbRU8ZvPhw==,type:comment]
    #ENC[AES256_GCM,data:xtQQ4fhaSJcj8BmJBIC7dGgHyPgYPO9iHJjRsjzTyUEVDc8=,iv:d5J9nqqOiNPOlTA6QKbKlwqrkZHbAijNo/cLs+G09bY=,tag:gO8KOUOxTo1Ubngve2FwlQ==,type:comment]
    #ENC[AES256_GCM,data:AK3m9WWZeK94OtYISfJyBuDGO3/aFwo9pF1Lp3gPSZUObPhFE3P5,iv:JAVBG2xU2hwBSVbZCbA6UtkboxYIvihtEp0k0FTHvMs=,tag:Sc8Dz/SzFJn3DI6VbYIc3g==,type:comment]
    #ENC[AES256_GCM,data:EmjegsoXaSf4XmNpI/I=,iv:5YQOEH8ShQuM6FCFWOiuuh3h+pmdLvY4tb4rHMB4Ono=,tag:aVTJyDYtt70NSbP9Rb/eLQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:j6g/SvrieBAjnW4BFg==,iv:IopkKlhP5sqV2NeGqpwZDfxkpHgx6Rzg1pvU9ZrVo0s=,tag:Wym/eCGgOT043gRr8kUQGg==,type:str]
    SVCNET: ENC[AES256_GCM,data:ozIA3hd0Lwm++8GG6A==,iv:LCJJS4c306CYV9SpYR4lnlvZAnbF2PyRvh0U9sdQwsw=,tag:T2GFnAzaT/4o2D0io/wrdg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:FB4Z5g==,iv:cJCsjmW649rsRNP8qA8ggXlHw8TCEZ3JDiU5Q12yp8A=,tag:8GnjJxIs0uWl93qglRdV0A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcekypmu7nuvegx4dwr5teq6fu2ryprmyefn2eq43s22tgx9z9vsz0hqzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQWxBUEtRaDJqU3Bjckwx
            S0w5dGcvWEhteEg0ME9KOGZ2bzlqMXl4Q2dvCnJBb1hyWDY2bWtUelN1NmNIQTNI
            cHdlRWhPYjBPS21obHJpV3hNR054OUUKLS0tIGhIYmdMS2Z4anM5Njltb0pKRmxw
            c1FrenV3cHJlalFIcGhyakFSQ1F1WXMKo5eHVia02WXUw4V9Uwu7jAn286NiWScz
            2uF0D/JPJXrN8MPcI70EkkXXbBkkeA/ruoJiEZjMAUiq8ADJmAJXUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T12:14:13Z"
    mac: ENC[AES256_GCM,data:8munBLDR2MLbQl+QvGGQFKOcwl5fRh82wcmwDs9X0TbOIlgDTlvs3nOgVzZ2ToGZQsWOTSwqm18wGbKocSv7SK2cbPhIk6Ia82tKWsxbsfjPLfeZsgMwhbfqBR58UsEtq18waLfc7xqovJgELy/YMUAV4LyJr0ggcsTydHVc/2E=,iv:1UbMLz63ZjZEudzh9gUXjwJuaGMSIieYgLS+7lZ5K6E=,tag:7O5b28Ww/gk6TYP6xkxJdw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
