apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:VrVcewl5p6ZB3kvd/VA1pfl5ez3AQVrRW1VQyHaX138bdXP7ZDUD5K7UvaLs5MPVC6FMUw3roGz9pfnAyCu/GFc=,iv:FVBQfbd3aHFlaZWoWhzvfug5KjLPjWCe6pXWUz75sc0=,tag:mvP3qbdqvnMyRCnCBcX5BA==,type:comment]
    #ENC[AES256_GCM,data:IuoC1uHp3wiK0q+6Xi332Y2x9ldo9uBxW9QmLi5r4iK3JIt4AZ6+ijZu2WI=,iv:/Bs3YbD7R46r3CchaIoaZ5Azo5eDkRyqWGy9bZr7SCU=,tag:IMrl1JoP/MyH9QRkvhnZSw==,type:comment]
    VIP: ENC[AES256_GCM,data:e1mzA72mzJ6B,iv:7p8q9lcnyKa1VKiy/w4tcITg0zSq4V/KoNvuy7ZyFLY=,tag:mHc4N5b3MkCCoB07Knf3Fg==,type:str]
    #ENC[AES256_GCM,data:oQcQDExXnYjxsh2Dooz8RD0ZyNmfe3swrNk=,iv:EdEdiErhe2tDWQtaxXdASdmlGph8Y+74Oh0QYhiE11w=,tag:dhKSLTsAYFxK5MVccaJc/g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:eGbUDkidt5Cv,iv:b2ErVx1Y8WLeqfq2jTaCN/N25Z2XoaEO3PjUISi3TCs=,tag:T3GptXzdXiq8ywIXMdBEOA==,type:str]
    #ENC[AES256_GCM,data:cLR8qbWYn1nWwqo2HJByhKxK4KOMn6s3Rn+GL3HS0t5MMw==,iv:SpF9bXOMDIorZ7/BZTulF3tKnY9lMAEJWSqkI6WjdrE=,tag:07rIc6p+/5sOIuu0sJvheA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:9gOFfx98PzE=,iv:lZDZ+v3uB0WD9DvgEzVjx3Sok4R/VK0Wtw5Fdmep5Q8=,tag:weEOzJjvb+lcXSBtTa5nVA==,type:str]
    #ENC[AES256_GCM,data:tFNKLUUqb0VE/fryKQPyj9LbC8kUar7TFw61TpQJuZ+m7BnI+Qv0vEwxPKooIJI=,iv:iWr/6BFSV3kSKoiqxDVKgUxWUE9mmcsJ8DbZIPWyB0E=,tag:hqKYluSCUh4/T5BF9g1KrA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:K1LvCTOr3mOo/EyutyQVhP6Jtw==,iv:xVAt1dZql8CTeNXTSwkXs2CDgvxF3MIO19m8wAGYR0A=,tag:VfU1FVDwRmnNVXwb65J74w==,type:str]
    #ENC[AES256_GCM,data:p1DJ/PjTCyp2iBDgjksuSPLEjr8ubB65RkEF81+plZ5o2tj2fQUUCxlduZ3/L+Pk6DK4iR5TGi5f3LJ3qNDBZKO1R+NoDbV9xdhqDjn8+QU=,iv:i5jhxsJOsIuKnatdIyfsVOL/Pnikj0U2GsQMJ3/XnvI=,tag:ArVl+fF0aMoTkHJbItvX/Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Qup0SAWaiZZl,iv:LU21dKUa8ZVBm/AaDhjbMt4XNcAlN7J7qUk095LRdmg=,tag:D6GuqjAPpwhcjTk5BgInXQ==,type:str]
    #ENC[AES256_GCM,data:XKcxKpmVhhkTcR5WO7IRicWzdnMbrlr644NMGU/RNqZmXKnYvaBaCvztO530abpwh1+ip96WANk=,iv:L1Uv6HXiQa1K4jRtA4wuLZW05BgwXFlHUbQe33C2Ghc=,tag:1cix1Kc/rQpYi5Rd4f1i8Q==,type:comment]
    #ENC[AES256_GCM,data:kjieyYhEgwUvrevW6ZjKep/xua/RXmeDiw==,iv:HOTDLVdZdpe6mZ1IHhOJwCoNR+oCjUF4pk7J8sm4XKw=,tag:kR9Qf1u76YoWnLA+Z3AmMQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:z8zWFxJpO3Jqv5Lmy5wllejJML/CZR9rOeZQVYbjGudVRbAkKXBKci5ggUULTA==,iv:9eMOf/cdj08/x61W02QIFLu5xAC96xWxVzxuisCq5UM=,tag:EvhzELObPbkZgKPhqzDLjQ==,type:str]
    #ENC[AES256_GCM,data:W/DSFEd3nWZZXmd+xQ==,iv:fdezd3yO+serS/hhkmwEtUiiy26tbdfUXwvG93tRqmY=,tag:p+/UirJeoaNI7MCzK7ZyVQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:XtzzBCx/cQs5mfxyAQ==,iv:bxWQ5w9s108NhHhRB4fMfvCBjX3UkZMcn1XE6Bq+W50=,tag:ROHeQJdyYQxMimVSrKTTuw==,type:str]
    SVCNET: ENC[AES256_GCM,data:pTaMXsHZSTc0IHbM3w==,iv:PcLqetOfCfs5IMEKLXPoyVkGzGpP0VMvTZ1mmJRhQ24=,tag:rNwYEYftB+2THUSumDcwEQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:8pz6Bg==,iv:GdAPLm042T6axCOtuYuAwDMF7CvOuXyUBVjy7/tWny0=,tag:syjcyyL7fGNr2F6lGNbCbA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yr5myyx9pszm3qcwnncl7w9qe88ahfftf4kv7r294cfctgagpyss7kqcxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZGZkSGN1VzdYSWlUaC9W
            d3hmMjlJVnpOMWhWejFKdnVTbWYyODFZZFc0CjFQK1RvVjNJSTZZam03WXVJNnVZ
            T3VrWXVZVFBHam0rSkErQkNUU2JXS0UKLS0tIHBzemNCelg5MVBkblhIeWJkd3ZT
            aXJCQkY5enhnSkdCRnNBODRDaFZ3UFUK95cNk8qQ7beJeIGONUBrMk0PhxNR29mw
            hFWMVU0DVM5pOgGQ7Ful19OIVjr0lSQ0Ft9PjJ1yFkyEfxQ9Asa2bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T05:35:11Z"
    mac: ENC[AES256_GCM,data:55SRmsYHXyCEhrQH73JILtBSMQH+ied68GCNiUfa9ePclFPRSZDShvmnG+p0EF/zOc40RBx3ygRmWxe8WUS3JZjUNFhNlC57N1XqggpAMqu8H8ASDBKbL44yxl7C0NrZezbTtQ5o4ZEoYaOVVsM78Bz7WIXBQAv/uTyY+jmmELM=,iv:mXPStExU+Hayv9L3D2l7zuHFFzwGhQWetboqKh3dX4I=,tag:SyH7Fl2LsmEz9Bc2dyatRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
