apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YRMOveJr1CqBMMZ+1frbJ9TdxICWB6Onx3l6Ukag7oAVU0qAdE3e722NGYU3mZvJXqz9ZNvvHLxn1ELLemGTIsdiBs5e+ugmDuuh2IYp0nGmzrKQqboh6kR9u0DkEx0ndwgEkdiMgveuaKOPvUsP1JPKofUn4zU0kWIXGMI0kj1qOXtzUW17FS00qH6FwsMv8usxcn/GArzTbPpohbz2kNEYL+5yXR8CauPWRYCfBJ87POO59S1vN1ogcVHoC+I2rM4mCJ5DALWi3GIC68nPrMYD27hcNdhWXCsLb2lPUV7DCn40bQaJrfKfXIziKHqn6vE1cC2330JBDcV3YCINncUpoEyBooKfslwP1QwmEbZriJZHpMXDwjpU1kC9GCLi,iv:ifUIAVgX7pKxDFi8IFYkFpZdZ9u5ESYARxSWRrmM2NI=,tag:L4tTd63I4XwfzJ4IpvZyfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Lf74K7Is/Bm9LIDC/80ULWFYdQ7GxPWsANJriBaxhllFb3ESw6ER0KVTTfJ12+M3DkG7Z0wIuo5AkR8mQUoLdcMPhF8g+tyzqG0AHxYzPsexrZt3EH5zj054ShxdKsMpSfuMr92oqP8V0eAKhzmNy5KMj1F2qJk+UHkHddGBNnlzw6c90OAIVhpjRcyMAVWffPcYN99E0l+UvaTr5bn7h+5ngLaCWVivTPASMtDbK0lTspzV6J0TPPnx1AoHv8wCasAidyXECuZQr6UZuQ==,iv:ITq8WDzRmED8u/tjRE5R1gLbPbaeIdYot5TxtBbH2yU=,tag:XiC4a3ZZhzEq0TDlcfk4nA==,type:str]
    known_hosts: ENC[AES256_GCM,data:v2zHozc7U4+n4HHgSZF9ZtRnI/9kxNu8aqyENE7Fp/ulA9woft2sjATiahtwHsJtQ7D8AkEuKZLEcryQEd5jDBTCPX9s8uV8lckG53SkdTTOKVLQiCeMa5vUEgeT0+oTEUfVg0c5bqzy4EyGzSRoTmaxwDsQWZ+jRy73Cn3X+aZk+Fotb1E0ekllX7Ffc62hZzVNrqLewWeL+lS7yUN7wggiLzx2QUW/m34a,iv:XylHiTciDY6ykXZLoXqbBknmjXloEaSt9j/GkskCSEY=,tag:RBVF78wMeatShhWiYWakLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcekypmu7nuvegx4dwr5teq6fu2ryprmyefn2eq43s22tgx9z9vsz0hqzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSmV0ZTJoa0xULzFxcDhn
            OU85TEFGTVFrcTBEaERjTFF0MkYxVEY4WTE4CjZjaUVzenh2Z1VQa3FEYVoxY0tV
            OThLalp6L3Vza2JvRk8yNC84czBBdU0KLS0tIHRYeHJMckViS1p5SE5yS1BpQnZz
            UUhnRkRFN25hNGJVNWcwSWNnRnBjWHcKRLOEWYdjnZ/NnWnbj4izcRxhTonr99qj
            IRnv711Y9FIyOjMoNoiFC+vUb01xPMIpB7CFUU7NgFC8l6egcov7xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T19:04:07Z"
    mac: ENC[AES256_GCM,data:rh24nx3sYelsj7REMpTdUcIYaRF8yL+3MHpZw8tuJPewdngxEbKbAi7mEIpkLd7dn5d9PppKUYehfU1faPkPChzwq2LKCFsLPtPUDKMyj0kflVj5O8NZ//KKE4pS2HqTp+2BgLMwv0n3m5Ga9CnRhgj76wU94Z+qEvHXIDDcm6A=,iv:cKKoXwiF9arVnbkrPCiWCLEQwyx17flWhztInYsAFeY=,tag:lPA/YJnouIMyO/tBS/i5XA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
