apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BovRKOnwLjl03AbY2k8uicc4oV8Fq/ziYFimtURmGuf9ectaaJwX2VvAvukqhSii/YU8CB2whpOmL9GKtwzH1NqAyjNOUS7wKJfcsIm+v/LT4FTzLdzyrWkb1Qy2oYYBMogBh4RIud33mIOXMmYlOkUTh1DRsBe3dk6KSw4BTc4xda/LCG7wsQST5F9GF4eePBVHRDMhVuU6MmilRAb/1XqFADajc9A1fFNeTF32f7X4rH8g1lrZ4Ni5vU749XZhCUXHBu29F33PMYwWbVASP0jHEqM6AJE/9UDDkxNggXEAS4vsTr8lc/2XILZCg40jSNYIao+53DKOQsnvSBtSiId4ywZVp1DKgqirdHRNCklO7I4/c/CGnLuGaFHes6u1,iv:3R6VesMhlz5MFc6tl/L6WeV7LkxT2AT8BjdoVNGz0dA=,tag:dOE11R58ICe8XsDBtmVD8g==,type:str]
    identity.pub: ENC[AES256_GCM,data:gmo5wIJgkHCn/kdf2xSSclatpePDEGihsTYzTLn/giBxWd4+C1301yumdLHySqLMuy5RAfwosmXodNC5RUGv7W9A8tkhV6MqmgxWCSnpwNsJpZ7hov+lNY/hbjUysNfg99rlWn9ZPdy+d2askTN27S46r9Zy3F//qqHzNb8q4wtsXjSeqHT2/0kbrp4IQrrtrfzwHvStiPZdRWoTP9suzuwcuxl5dLnnfXwTbY1IHaS+bIrNL+JlMaGC6zEWip1Np4hywau5grM6mqakXg==,iv:3/GuXmb+BoEEYkn+NLZPr4ykcVC4am/AQsoTUehQYmY=,tag:Qa7hxZbFbD57lozyDivXsw==,type:str]
    known_hosts: ENC[AES256_GCM,data:R/BdDn7zTjOvTTGl4IucUPIzTuXX4j9M6zxPQcXxdO2Ql2jOvcQ6+l0sxKIBHskU4eDZvsjX+0Dj6v09Ng2l2guxcZVsbgAtRpMtUcLlJ0wVWPM0q8awIfA208yJbXL9v65eZmjGYIGZycQ/j/hXqJx1/2SNUUnzFIxGsX6PkjiRRWn7OfbPQsBdTYeAZdzrrNUzGzRFEAkTIq1i522/FYNa68lCE916uBWD,iv:a57H0qeW+eJL0DMdK2aMwgZ85dP1UVE5Z1SWdVdGKdw=,tag:bUln00xSGJoncFLAsC8X2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcekypmu7nuvegx4dwr5teq6fu2ryprmyefn2eq43s22tgx9z9vsz0hqzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscWlTV3JycmNTZGt4czZu
            RnZaTURlL2hWTTU5aFhONnp1NUxhdzFGMFdBCk91U3RJR3ZreDBIbFkvQVFodlBq
            V2gwK3NLNWlrR0xoY0lSS3p4YjVkQWMKLS0tIFhldHB1U21BK3NyTU52NTB4ckkz
            Qk5uOXI1S1NxRHdHSXV3cS85TjVXODAKN7OBC8ljxxDw9JKsHoaTZ8Lt3aZRMQnk
            qLQbF1A9b8HRqvQAx+4Ph/v6HC2TrkLA7Qn2tWz2ZpGBesdpboTBpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T12:28:47Z"
    mac: ENC[AES256_GCM,data:ucy20A+zVwYRTUDHtx6hR98GQ+LT4UwPAK29ArktYASpQYrSA4zmxukh98qAsI2QRXGPdSd1a6v3laQgqpbMC4MxO+dzH0rIqeAaI2yDgA+vLQBBLvzImOU76yJTgC/Mvs5LUeSsbIZ/uFSXs4QWbY4XayghJgTzP2AZhgn7AgA=,iv:z4X3AU721galLh4lDXgnKM7mT0/Rf/mD4YVhgveBQ44=,tag:pC/FTc+XmRLEZRmQu3PfMw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
