apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:T2XuSuhBj6v7Ub+2wPfV1PG+I7hCUP9tpdiV9EKdJ+PmnafYIq/AKAksjn0AHuezIg5EFzgZTsQwgTs8Nw6BjmB/qL7JX7Mol0rnxFnJ/ZWzQmOB5glNIwAO9rET4Js4KsPzXMBCoNj1Ivgq23/JZYm5NnxaC9++EZKD9QSdcptGukUrTwQH9IeJrfAl+0iK25xWDwLMN8t17alaQeRaITbt7Z7OOq9wzOk8yCnswT+TbE/TTxuSAMBYMClQU+5aBjDLINoRqhlotsgVf0t5Ndm0Gdkv+/WVl23d6SdI3YA/GL4zDHxfPwD4vmB6TVpLs0tsP1OnZ8SlfS3OOJacPj2e3K/m5wB253iMLqJxwsOnDQfafzY5Oi7xaNQSZn5U,iv:7tbkUN+yEhgWaPLOtMIqbvGfnG+WljybyOnVXA0BTao=,tag:BJ9qIQH2Ywi0H6L5Nn73qA==,type:str]
    identity.pub: ENC[AES256_GCM,data:me3cnvcxsu8QaqENwDX9xB0cuwOafu7omvz5cgwRyFX0+3rKL/iqPrEV1VzfvxlSkzFl6ppjf82MpspIj14X65SeOue/lQqqRJH/tQMdbiHWz7du53okr44qc2SFMb6e/G3isTPBbhx+pEq8oATK9b6yaRARCC0Ra54rIyM6YRy+r5uOtC3Ogi/BfSR2UBgpUlb2njXFuOjDSGPa4YGUE9SxiRA2h5FSZe4nCxm9nor3UnEHZET7vzFPlpegyseDxpi3WNVFKnS8zXPwjQ==,iv:LsepQFZoleH4Q4oru7htpSZJziYUrvqpKx9ojOl3oc8=,tag:iUmb2TR/YHs7boqRGuM+kg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Gcdxifcj51zJdVWY+lcNlqb2qWaYPKpJ/7/6WjaCaYhwAmEPgXa6+pBFJcsvnx8Syn0dqoKTCU3Gt1E47ab7mJ7Znfb2rp4UQsVDlxhQ+w9ywvtYsUColTs5sa3C/hQSfmBSmgkbbxaGZFKXrdmw6EGr432/HxyCf15v/ijlKzvhn7ffaHRiao3QGjP6phFfv+PtEx/pssiPUxdsFgSCS9mGiWJrxznQXipM,iv:9HllXgFoqJEcVJ+d1BIjJ2b1eMVcfB0UhwJdfZimkk0=,tag:m7M92j/6shZp/PAWgoYsgg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yr5myyx9pszm3qcwnncl7w9qe88ahfftf4kv7r294cfctgagpyss7kqcxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRXREdzVaYUdrVFpIMkUw
            S2c5RDQzb1NIZXp3LzJ2cUlMSklhM1VUWTMwCjArUlRQck5aQWxUWWpMUmRjOW1E
            VHBrUkxHb3pjTmZVbGlZK1MrNVlrNlkKLS0tIDltQlJjM1E2UGFwVzMwVExTMk9N
            dllzN2Q5alNnWERtQlh4VEc2RGhkbE0KoBYPEula4by7J91BnnS5z3SBA+ssRxjk
            Oeu1f5UpJ5l5BVslUtgLgVUo5DYTJBVgRMiqNzRCUKYSCzA+Ogv3yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T05:35:12Z"
    mac: ENC[AES256_GCM,data:xB1hAgqglEaM9G4n88M8bnrB31FP3eVZqA5V1+Z+h13uT9dvAKSdHWXgZL9JMcYUEflq7Sl89D5q0o7VdCwiSKsoTBRd2cP/O22FHDOWIHMUl6ldCkC0Xu5cBTtnhMP/ouphIUzVPo/GhAKpj5nzSTw3TsLfnZPvj8+kKtDWf1o=,iv:dgB4GbJpQ70p0zK1te8bjJsO0xZc2YHD40UCF3bsV/8=,tag:2dSeZn8fs1hALYiGLri7SA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
