---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: librespeed
    namespace: librespeed
spec:
    interval: 15m
    chart:
        spec:
            chart: librespeed
            version: 15.3.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: librespeed
    values:
        TZ: Europe/Vienna